CREATE TABLE IF NOT EXISTS player_simulations (
  player_id INTEGER PRIMARY KEY,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  runs INTEGER NOT NULL,
  mean_points DOUBLE PRECISION NOT NULL,
  median_points DOUBLE PRECISION NOT NULL,
  p10 DOUBLE PRECISION NOT NULL,
  p25 DOUBLE PRECISION NOT NULL,
  p75 DOUBLE PRECISION NOT NULL,
  p90 DOUBLE PRECISION NOT NULL,
  std_dev DOUBLE PRECISION NOT NULL,
  haul_probability DOUBLE PRECISION NOT NULL,
  floor_probability DOUBLE PRECISION NOT NULL,
  ceiling_probability DOUBLE PRECISION NOT NULL,
  captain_ev DOUBLE PRECISION NOT NULL,
  coefficient_variation DOUBLE PRECISION
);
